tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    path('details/<int:pk>', views.TaskDetailsView.as_view(), name='details'),
    path('edit/<int:pk>', views.TaskEditView.as_view(), name='edit'),
    path('export/', views.TaskExportView.as_view(), name='export'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    # path('favicon.ico', RedirectView.as_view(url='/favicon.ico', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class TodoItem(models.Model):
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, 'Высокий приоритет'),
        (PRIORITY_MEDIUM, 'Средний приоритет'),
        (PRIORITY_LOW, 'Низкий приоритет'),
    ]

    description = models.CharField(max_length=64)
    is_completed = models.BooleanField('Completed', default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='tasks')
    priority = models.IntegerField('Приоритет',
                                   choices=PRIORITY_CHOICES,
                                   default=PRIORITY_MEDIUM)

    def __str__(self):
        return self.description.lower()

    class Meta:
        ordering = ('-created', )

    def get_absolute_url(self):
        return reverse('tasks:details', args=[self.pk])

tasks/forms.py
from django import forms
from tasks.models import TodoItem


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('description', 'priority', )
        labels = {'description': 'Описание', 'priority': ''}
        widgets = {
            'description': forms.TextInput(attrs={'class': 'form-control mb-2',
                                                  'placeholder': 'Описание'}),
            'priority': forms.Select(attrs={'class': 'form-control mb-2'})
        }


class TodoItemExportForm(forms.Form):
    priority_high = forms.BooleanField(label='высокой сложности',
                                       initial=True,
                                       required=False)
    priority_medium = forms.BooleanField(label='средней сложности',
                                         initial=True,
                                         required=False)
    priority_low = forms.BooleanField(label='низкой сложности',
                                      initial=False,
                                      required=False)

tasks/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from tasks.models import TodoItem
from tasks.forms import TodoItemForm, TodoItemExportForm
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse
from django.contrib import messages


@login_required
def index(request):
    return HttpResponse("Примитивный ответ из приложения tasks")


def complete_task(request, uid):
    task = TodoItem.objects.get(pk=uid)
    task.is_completed = True
    task.save()
    return HttpResponse('OK')


def delete_task(request, uid):
    task = TodoItem.objects.get(pk=uid)
    task.delete()
    messages.success(request, 'Задача удалена')
    return redirect(reverse('tasks:list'))


class TaskListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = 'tasks'
    template_name = 'tasks/list.html'

    def get_queryset(self):
        user = self.request.user
        return user.tasks.all()


class TaskCreateView(View):
    def create_render(self, request, form):
        return render(request, 'tasks/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect(reverse('tasks:list'))

        return self.create_render(request, form)

    def get(self, request, *args, **kwargs):
        form = TodoItemForm
        return self.create_render(request, form)


class TaskDetailsView(DetailView):
    model = TodoItem
    template_name = 'tasks/details.html'


class TaskEditView(LoginRequiredMixin, View):
    def create_render(self, request, form, task):
        return render(request, 'tasks/edit.html', {'form': form, 'task': task})

    def post(self, request, pk, *args, **kwargs):
        task = TodoItem.objects.get(id=pk)
        form = TodoItemForm(request.POST, instance=task)
        if form.is_valid():
            updated_task = form.save(commit=False)
            updated_task.owner = request.user
            updated_task.save()
            return redirect(reverse('tasks:list'))

        return self.create_render(request, form, task)

    def get(self, request, pk, *args, **kwargs):
        task = TodoItem.objects.get(id=pk)
        form = TodoItemForm(instance=task)
        return self.create_render(request, form, task)


class TaskExportView(LoginRequiredMixin, View):
    def generate_body(self, user, priorities):
        q = Q()
        if priorities['priority_high']:
            q = q | Q(priority=TodoItem.PRIORITY_HIGH)
        elif priorities['priority_medium']:
            q = q | Q(priority=TodoItem.PRIORITY_MEDIUM)
        elif priorities['priority_low']:
            q = q | Q(priority=TodoItem.PRIORITY_LOW)

        tasks = TodoItem.objects.filter(owner=user).filter(q).all()

        body = 'Ваши задачи и приоритеты: \n'
        for task in list(tasks):
            if task.is_completed:
                body += f'[x] {task.description} ({task.get_priority_display()})\n'
            else:
                body += f'[ ] {task.description} ({task.get_priority_display()})\n'

        return body

    def post(self, request, *args, **kwargs):
        form = TodoItemExportForm(request.POST)
        if form.is_valid():
            email = request.user.email
            body = self.generate_body(request.user, form.cleaned_data)
            send_mail('Задачи', body, settings.EMAIL_HOST_USER, [email])
            messages.success(request, f'Задачи были отправлены на почту {email}')
        else:
            messages.error(request, 'Что-то пошло не так, попробуйте ещё раз')
        return redirect(reverse('tasks:list'))

    def get(self, request, *args, **kwargs):
        form = TodoItemExportForm()
        return render(request, 'tasks/export.html', {'form': form})

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Создать задачу {% endblock %}

{% block main_content %}
    <h1>Создать задачу</h1>
    <form action="." method="post">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <div class="col-12">
                <label class="sr-only" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                {{ form.description }}
            </div>
            <div class="col-12">
                {{ form.priority }}
            </div>
        </div>
        <button class="btn btn-dark" type="submit">Добавить</button>
    </form>
{% endblock %}

tasks/templates/tasks/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Задача {{ object.id }} {% endblock %}
{% block extra_head %}
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
          crossorigin="anonymous"
    >
{% endblock %}

{% block main_content %}
<h1>Задача {{ object.id }}</h1>
<p><b>Описание</b>: {{ object }}</p>
<ul>
    <li>{{ object.is_completed|yesno:'Выполнена,Не выполнена' }}</li>
    <li><i class="far fa-calendar-alt"></i>&nbsp;Создана: {{ object.created|date:'d.m.Y H:i' }}</li>
    <li><i class="far fa-clock"></i>&nbsp;Последнее изменение: {{ object.updated|date:'d.m.Y H:i' }}</li>
    <li><i class="far fa-edit"></i>&nbsp;<a href="{% url 'tasks:edit' pk=object.pk %}">Редактировать</a></li>
</ul>
<i class="fas fa-list-ul"></i>&nbsp;<a href="{% url 'tasks:list' %}">Назад к списку </a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends 'base.html' %}

{% block title %} Изменить задачу {% endblock %}

{% block main_content %}
    <h1>Поменять задачу</h1>
    <form action="{% url 'tasks:edit' task.pk %}" method="post">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <div class="col-12">
                <label class="sr-only" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                {{ form.description }}
            </div>
            <div class="col-12">
                {{ form.priority }}
            </div>
        </div>
        <button class="btn btn-dark" type="submit">Сохранить</button>
    </form>
{% endblock %}

tasks/templates/tasks/export.html
{% extends 'base.html' %}

{% block title %} Экспорт {% endblock %}

{% block main_content %}
    <h1>Экспорт задач</h1>
    <p>На вашу почту придёт емейл с задачами. Уточните список.</p>
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><button class="add" type="submit">Жмяк</button></p>
    </form>
{% endblock %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Задачи на день {% endblock %}

{% block extra_head %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

{% block main_content %}
    <h1>Текущие задачи</h1>
    <ul id="list-group">
        {% for task in tasks %}
            {% if task.is_completed %}
                <li class="list-group-item completed">
                    <input class="checkbox" data-uid="{{ task.id }}" type="checkbox" disabled="disabled" checked="checked" />
            {% else %}
                <li class="list-group-item">
                    <input class="checkbox" data-uid="{{ task.id }}" type="checkbox" />
            {% endif %}
            {% if task.priority == task.PRIORITY_HIGH %}
                <span class="badge badge-pill badge-danger">&nbsp;</span>
            {% elif task.priority == task.PRIORITY_MEDIUM %}
                <span class="badge badge-pill badge-warning">&nbsp;</span>
            {% elif task.priority == task.PRIORITY_LOW %}
                <span class="badge badge-pill badge-success">&nbsp;</span>
            {% endif %}
            <a href="{% url 'tasks:details' task.id %}">{{ task }}</a>
            <a class="remove" href={% url 'tasks:delete' task.id %}>X</a>
            <hr/>
        </li>
        {% endfor %}
    </ul>
{% endblock %}