tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    path('details/<int:pk>', views.TaskDetailsView.as_view(), name='details'),
    path('edit/<int:pk>', views.TaskEditView.as_view(), name='edit'),
    path('export/', views.TaskExportView.as_view(), name='export'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    # path('favicon.ico', RedirectView.as_view(url='/favicon.ico', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Tasks list {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    {% block extra_head %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="side_bar col">
                {% block side_bar %}
                    {% if user.is_authenticated %}
                        <p class="h4">Имя: {{ user.first_name }}</p>
                        {% comment %}{% if user.profile.avatar.url != None %}
                            <img src="{{ user.profile.avatar.url }}" class="img-fluid">
                        {% else %}
                            <img src="/media/no_image.png" class="img-fluid">
                        {% endif %}{% endcomment %}
                        <ul class="nav flex-column">
                            <li class="nav-item"><a href="{% url 'edit' %}" class="nav-link">профиль</a></li>
                            <li class="nav-item"><a href="{% url 'tasks:create' %}" class="nav-link">добавить задачу</a></li>
                            <li class="nav-item"><a href="{% url 'tasks:list' %}" class="nav-link">задачи</a></li>
                            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">выйти</a></li>
                        </ul>
                    {% endif %}
                {% endblock %}
            </div>
            <div class="main_content col-8">
                {% if messages %}
                    <div class="row">
                        <ul class="messages">
                            {% for message in messages %}
                                <li class="alert alert-{{ message.tags }} alert-dismissible">
                                    {{ message }}
                                    <a href="#" class="close" data-dismiss="alert">x</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% block main_content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>